/*
const Mizuki = require('../events');
const { MessageType } = require('@adiwajshing/baileys');
const Config = require('../config');
if (Config.LANG == 'SI') AS_DESC = 'Mizuki හි SUDO හා එම නම්බර් එකට පමණක් භාවිත කල හැකි විධාන පෙන්වයි.'
if (Config.LANG == 'EN') AS_DESC = 'Shows commands that can only be used for Mizuki\'s SUDO and that number.'
const msg = "🛠 Command: .vtalk\n💬 Description: Mizuki සිය voice සංවාදය ආරම්භ කරයි.\n\n🛠 Command: .fulleva\n💬 Description: සම්පුර්ණ ක්‍රියාකාරී Eva විශේෂාංග සක්‍රීය කරයි. ඔබේ ගිණුම චැට්බෝට් එකක් බවට පත් කරන්න!\n⌨️ Example: .fulleva on / off\n\n🛠Command: .install \n💬 Description: බාහිර ප්ලගීන ස්ථාපනය කරන්න.\n⚠️ Warn: Get plugins only from my GitHub :- https://gist.github.com/MrJoka-Thejaka\n\n🛠 Command: .plugin\n💬 Description: ඔබ ස්ථාපනය කර ඇති ප්ලගින පෙන්වයි.\n\n🛠 Command: .remove\n💬 Description: ප්ලගිනය ඉවත් කරයි.\n\n📕Command: .vtalk\n📖Description: Mizuki සිය voice සංවාදය ආරම්භ කරයි.\n\n📕Command: .xmedia\n📖Description: එය මාධ්‍ය සංස්කරණ මෙවලම් 25 කට වඩා ඇති ප්ලගිනයකි.\n\n📕Command: .locate\n📖Description: එය ඔබගේ Location එක එවයි.\n⚠️ Warn: කරුණාකර මෙම විධානය ක්‍රියා කරවීමට පෙර ඔබේ location on කරන්න!\n\n📕Command: .afk\n📖Description: එය on කල විට ඔබ ඕෆ්ලයින් යැයි බොට් පවසයි\n\n📕Command: .deepai\n📖Description: Artificial neural networks උපයෝගී කරගනිමින් ප්‍රබල AI මෙවලම් ක්රිුයාත්මක කරයි.\n\n📕Command: .print\n📖Description: එය Server එක තුළ ශ්‍රව්‍ය, දෘශ්ය හා ඡායාරූප ගබඩා කරනු ලබයි.\n\n📕Command: .bashmedia\n📖Description: එය Server එක තුළ ශ්‍රව්‍ය, දෘශ්ය හා ඡායාරූප ගබඩා කරයි.\n📖Example: video.mp4 && media/gif/pic.mp4\n\n📕Command: .addserver\n📖Description: Server එකට රූප, ශ්‍රව්‍ය හෝ වීඩියෝ upload කරයි.\n\n📕Command: .term\n📖Description: Allows to run the command on the server's shell.\n\n📕Command: .degis\n📖Description: Changes the text of modules like alive, afk etc..\n\n📕Command: .log\n📖Description: Saves the message you reply to your private number.\n⚠️ Warn: Does not support animated stickers!\n\n📕Command: .notes\n📖Description: ඔබගේ දැනට පවතින සියලුම සටහන්(notes) පෙන්වයි.\n\n📕Command: .save\n📖Description: Reply a message and type .save or just use .save <Your note> without replying\n\n📕Command: .deleteNotes\n📖Description: Deletes all your saved notes.\n\n📕Command: .pp\n\n📖Description: ඔබ මෙන්ශන් දුන් ඡායාරූපය Profile Picture එක ලෙස සකසයි.\n\n📕Command: .scam\n📖Description: මිනිත්තු 5 ක ව්යාeජ ක්රිuයා නිර්මාණය කරයි.\n\n📕Command: .update\n📖Description: ඔබට නව යාවත්කාලීන කිරීම්(updates) පැමිණ ඇත්දැයි පරීක්ෂා කිරීමට.\n\n📕Command: .update now\n📖Description: Mizuki අප්ඩේට් කරයි.\n\n📕Command: .speedtest📖Description: ඩවුන්ලෝඩ් හා අප්ලෝඩ් කිරීමේ වේගය මැනයි.\n\n📕Command: .ping\n📖Description: Measures your ping."

Mizuki.addCommand({pattern: 'admin$', fromMe: wk, desc: AS_DESC}, (async (message, match) => {
  
   await message.client.sendMessage(message.jid, msg, MessageType.extendedText, { contextInfo: { mentionedJid: jids }, previewType: 0 })
 
    }
                                                                   
                                */                                   
                                                                   
